### ISSUE TITLE
Project proposal feedback

### ISSUE THREAD

**Issue by platisd** [DIT112-V20/group-05#13]
To begin with, I don't see the point with the GPS. It will be hard to demo (as probably discussed during out meeting) and since you are having the car follow a black tape, it adds no value to the overall presentation. If you really want to visualize on the map, just fake the coordinates coming from the car.

In order to avoid additional hardware, I would suggest you skip the black tape too. Can we have it just move (e.g. randomly) until it finds an obstacle? When an obstacle is found the control will be given to the user and if you want you can fake a stream of GPS coordinates from the car.

**Comment by JakobRoseke** [comment]
About the GPS, we are not going to use a GPS. It could have been some misunderstanding.
We were thinking of doing the "fake coordinates map" in some way to indicate how far you have gotten on the path, that has a predetermined length.

We agree with the black tape feedback, especially with our current situation we want to keep it as simple as possible whilst still creating the system we want.
We will, most likely, make the car move automated until an obstacle and either turn off or change it to manual mode in order to move the car.

**Comment by platisd** [comment]
Sounds cool, let's see how it goes
